   var dependencies = {
    links:
      [
            { "source" : "AppDelegate", "dest" : "VKSdk" },
            { "source" : "main", "dest" : "AppDelegate" },
            { "source" : "NGCommunitiesViewController", "dest" : "NGCommunitiesTableViewCell" },
            { "source" : "NGCommunitiesViewController", "dest" : "NGServerManager" },
            { "source" : "NGGetWallObjectData", "dest" : "NGLinkObjectData" },
            { "source" : "NGGetWallObjectData", "dest" : "NGMusicObjectData" },
            { "source" : "NGGetWallObjectData", "dest" : "NGPhotoObjectData" },
            { "source" : "NGMyFriendsViewController", "dest" : "NGMyFriendsTableViewCell" },
            { "source" : "NGMyFriendsViewController", "dest" : "NGServerManager" },
            { "source" : "NGProfileViewController", "dest" : "NGServerManager" },
            { "source" : "NGProfileViewController", "dest" : "SCLAlertView" },
            { "source" : "NGProfileViewController", "dest" : "VKSdk" },
            { "source" : "NGServerManager", "dest" : "AFHTTPRequestOperationManager" },
            { "source" : "NGServerManager", "dest" : "NGAccessToken" },
            { "source" : "NGServerManager", "dest" : "NGGetCommunitiesObjectData" },
            { "source" : "NGServerManager", "dest" : "NGGetFriendsObjectData" },
            { "source" : "NGServerManager", "dest" : "NGGetUserObjectData" },
            { "source" : "NGServerManager", "dest" : "NGGetWallObjectData" },
            { "source" : "NGServerManager", "dest" : "NGPhotoObjectData" },
            { "source" : "NGServerManager", "dest" : "VKApi" },
            { "source" : "NGServerManager", "dest" : "VKBatchRequest" },
            { "source" : "NGServerManager", "dest" : "VKImageParameters" },
            { "source" : "SidebarViewController", "dest" : "SWRevealViewControllerSegue" },
            { "source" : "SWRevealViewController", "dest" : "SWDirectionPanGestureRecognizer" },
            { "source" : "SWRevealViewController", "dest" : "SWRevealView" },
            { "source" : "SWRevealViewController", "dest" : "SWRevealViewControllerSegue" },
            { "source" : "NGCommunitiesViewController", "dest" : "SWRevealViewController" },
            { "source" : "NGCommunitiesViewController", "dest" : "NGCommunitiesTableViewCell" },
            { "source" : "NGCommunitiesViewController", "dest" : "NGGetCommunitiesObjectData" },
            { "source" : "NGGetWallObjectData", "dest" : "NGGetUserObjectData" },
            { "source" : "NGGetWallObjectData", "dest" : "NGPhotoObjectData" },
            { "source" : "NGGetWallObjectData", "dest" : "NGLinkObjectData" },
            { "source" : "NGGetWallObjectData", "dest" : "NGMusicObjectData" },
            { "source" : "NGMyFriendsViewController", "dest" : "NGGetUserObjectData" },
            { "source" : "NGMyFriendsViewController", "dest" : "NGGetCommunitiesObjectData" },
            { "source" : "NGMyFriendsViewController", "dest" : "SWRevealViewController" },
            { "source" : "NGMyFriendsViewController", "dest" : "NGMyFriendsTableViewCell" },
            { "source" : "NGMyFriendsViewController", "dest" : "NGGetFriendsObjectData" },
            { "source" : "NGMyPhotosViewController", "dest" : "SWRevealViewController" },
            { "source" : "NGProfileViewController", "dest" : "NGGetUserObjectData" },
            { "source" : "NGProfileViewController", "dest" : "SWRevealViewController" },
            { "source" : "NGProfileViewController", "dest" : "VKAccessToken" },
            { "source" : "NGProfileViewController", "dest" : "VKError" },
            { "source" : "NGProfileViewController", "dest" : "VKRequest" },
            { "source" : "NGProfileViewController", "dest" : "VKRequestTiming" },
            { "source" : "NGProfileViewController", "dest" : "SCLAlertView" },
            { "source" : "NGProfileViewController", "dest" : "NGFirstCollectionViewCell" },
            { "source" : "NGProfileViewController", "dest" : "NGPhotoProfileCollectionViewCell" },
            { "source" : "NGProfileViewController", "dest" : "NGPhotoObjectData" },
            { "source" : "NGServerManager", "dest" : "NGAccessToken" },
            { "source" : "NGServerManager", "dest" : "AFHTTPRequestOperationManager" },
            { "source" : "NGServerManager", "dest" : "AFHTTPRequestSerializer" },
            { "source" : "NGServerManager", "dest" : "AFHTTPResponseSerializer" },
            { "source" : "NGServerManager", "dest" : "AFSecurityPolicy" },
            { "source" : "NGServerManager", "dest" : "AFNetworkReachabilityManager" },
            { "source" : "NGServerManager", "dest" : "NGGetUserObjectData" },
            { "source" : "NGServerManager", "dest" : "AFHTTPRequestOperation" },
            { "source" : "SidebarViewController", "dest" : "SWRevealViewControllerSegue" },
            { "source" : "SWRevealViewController", "dest" : "SWRevealView" },
            { "source" : "SWRevealViewController", "dest" : "SWDirectionPanGestureRecognizer" },
            { "source" : "SWRevealViewController", "dest" : "SWRevealViewControllerSegue" },
            { "source" : "SWRevealViewController", "dest" : "FrontViewPosition" },
         ]
    }
  ;
